a = input('Digite algo: ')
print('O tipo primitivo desse valor é',type(a))
print('so tem espaços?', a.isspace)
print('ta em maiusculas?', a.isupper)
print('é um numero?', a.isnumeric)
print('é alfabetico?', a.isalpha)
print('é alfanumerico?', a.isalnum)
print('esta em minuscula?', a.islower)
print('Esta capitalizada?', a.istitle)